#!/usr/bin/env ruby

git_bundles = [
  "git://github.com/ervandew/supertab.git",
  "git://github.com/tpope/vim-sleuth",
  "git://github.com/godlygeek/tabular.git",
  "git://github.com/pangloss/vim-javascript.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/mattn/emmet-vim.git",
  "git://github.com/altercation/vim-colors-solarized",
  "git://github.com/majutsushi/tagbar.git",
  "git://github.com/rizzatti/funcoo.vim.git",
  "git://github.com/bling/vim-airline",
  "git://github.com/klen/python-mode.git",
  "git://github.com/heavenshell/vim-jsdoc",
  "git://github.com/mxw/vim-jsx",
  "git://github.com/tpope/vim-ragtag",
  "git://github.com/bronson/vim-trailing-whitespace",
  "git://github.com/kien/ctrlp.vim",
  "git://github.com/Yggdroot/indentLine",
  "git://github.com/honza/vim-snippets",
  "git://github.com/SirVer/ultisnips",
  "git://github.com/ervandew/matchem",
  "git://github.com/scrooloose/syntastic.git"
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
